### ISSUE TITLE
NoClassDefFoundError: KafkaConsumerMetrics after upgrading to 0.12.0

### ISSUE THREAD

**Issue by mitasov-ra** [Tinkoff/kora#187]
I bumped Kora version to 0.12.0 and previously working app now fails on startup with the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: ru/tinkoff/kora/kafka/common/consumer/telemetry/KafkaConsumerMetrics
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
    at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
    at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(Unknown Source)
    at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source)
    at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source)
    at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Unknown Source)
    at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source)
    at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source)
    at java.base/sun.reflect.generics.repository.FieldRepository.computeGenericType(Unknown Source)
    at java.base/sun.reflect.generics.repository.FieldRepository.getGenericType(Unknown Source)
    at java.base/java.lang.reflect.Field.getGenericType(Unknown Source)
    ... and then trace of my app, in generated ApplicationGraph
```

I do not have any Kafka related dependencies and settings in my project.

Kora version: 0.12.0
Kotlin version: 1.8.22
KSP version: 1.8.22-1.0.11
